---
data:
 token: 'Bearer BQDFqo4nzmSKLz91Sq7sQ45K5Dm7MPdJKbrUT-Gk87owRn7GkkUyADLQCOtqommWbtIiT3Cz1TmfmadaxhZq3_0KmHlHwVmUv_EkGYcis95k7iPRceLoDM2X5G_Cg7jfNga4V36mXCeLZC18PyZ1fN2il5rLe_WpvWOqth9YDb5m47wbgVz0uCNgkncimZroqw'
 token_expirado: 'Bearer BQDsAEQgn4q2HaS-SjdcEwGW9CvA2MYHVEOIVix0kuILa3tCRgM0qd0FHyMogxcMaDO07r_ZHJYUgsJQswvQfYwjClJqzN0P_Yle9A2m_g-e5w7wWI7qJjN0ZCb0BTNWEmF-KV7wkB_Pv5J6SgKwqkwoUdKdngcD9XTBJvRmOpHvbJ725HvhkAqszW8IpLMrJg'
 uri_track: '{"uris": ["spotify:track:4iV5W9uYEdYUVa79Axb7Rh"]}'
 uri: 'spotify:track:4iV5W9uYEdYUVa79Axb7Rh'
